[package]
name = "SIS"
version = "0.1.0"
edition = "2024"

[dependencies]
bls12_381 = {version= "0.8.0", features = ["experimental"]}
pairings = { git = "https://github.com/kamel78/efficient-rust-pairings.git", branch = "main" }
