name: twinsa
description: "TwINSA Live Streaming Service"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  mqtt_client: ^10.2.0
  camera_windows: ^0.2.1
  camera_platform_interface: ^2.5.0
  cross_file: ^0.3.3
  typed_data: ^1.3.2
  audioplayers: ^6.5.1
  record: ^6.1.2
  record_windows: ^1.0.4
  permission_handler: ^12.0.1
  path_provider: ^2.1.1
  flutter_sound: 9.2.13
  mp_audio_stream: ^0.2.2


dependency_overrides:
  record_linux: ^1.0.0
  record_platform_interface: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true